const BASE_API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost/emr-backend-l11/public/api';

const ENDPOINTS = {
    // GET METHODS
    GET_PATIENT_LIST: `${BASE_API_URL}/patient/get-list`,
    GET_APPOINTMENTS: `${BASE_API_URL}/appointments`,
    GET_PATIENT_HISTORY: `${BASE_API_URL}/patient-history`,
    GET_EXAMINATION: `${BASE_API_URL}/examination`,
    GET_SPECIALITY: `${BASE_API_URL}/speciality/index`,
    GET_SPECIALITY_LIST: `${BASE_API_URL}/speciality/get-list`,
    GET_REREFENCE_LIST: `${BASE_API_URL}/reference/get-list`,
    GET_PURCHASER_LIST: `${BASE_API_URL}/purchaser/get-list`,
    GET_DOCTOR_LIST: `${BASE_API_URL}/doctor/get-list`,
    GET_PURCHASER_TYPE_LIST: `${BASE_API_URL}/purchaser-type/get-list`,

    // POST METHODS    
    POST_DROPDOWN: `${BASE_API_URL}/dropdown`,
    POST_CREATE_PATIENT: `${BASE_API_URL}/store`,
    POST_DOCTOR_LIST: `${BASE_API_URL}/doctor/index`,
    POST_DOCTOR_FORMDATA: `${BASE_API_URL}/doctor/form-data`,
    POST_DOCTOR_STORE: `${BASE_API_URL}/doctor/store`,
    POST_DOCTOR_ARCHIVE: `${BASE_API_URL}/doctor/archive`,
    POST_PATIENT_CATEGORY_LIST: `${BASE_API_URL}/patient-type/index`,
    POST_PATIENT_CATEGORY_FORMDATA: `${BASE_API_URL}/patient-type/form-data`,
    POST_PATIENT_CATEGORY_ARCHIVE: `${BASE_API_URL}/patient-type/archive`,
    POST_PATIENT_CATEGORY_STORE: `${BASE_API_URL}/patient-type/store`,
    POST_PROCEDURE_LIST: `${BASE_API_URL}/procedure/index`,
    POST_PROCEDURE_GETLIST: `${BASE_API_URL}/procedure/get-list`,
    POST_PROCEDURE_FORMDATA: `${BASE_API_URL}/procedure/form-data`,
    POST_PROCEDURE_ARCHIVE: `${BASE_API_URL}/procedure/archive`,
    POST_PROCEDURE_STORE: `${BASE_API_URL}/procedure/store`,
    POST_SPECIALITY_LIST: `${BASE_API_URL}/speciality/index`,
    POST_SPECIALITY_FORMDATA: `${BASE_API_URL}/speciality/form-data`,
    POST_SPECIALITY_ARCHIVE: `${BASE_API_URL}/speciality/archive`,
    POST_SPECIALITY_STORE: `${BASE_API_URL}/speciality/store`,
    POST_CONTACT_LIST: `${BASE_API_URL}/contact/index`,
    POST_CONTACT_FORMDATA: `${BASE_API_URL}/contact/form-data`,
    POST_CONTACT_ARCHIVE: `${BASE_API_URL}/contact/archive`,
    POST_CONTACT_STORE: `${BASE_API_URL}/contact/store`,
    POST_FACILITY_LIST: `${BASE_API_URL}/location/index`,
    POST_FACILITY_FORMDATA: `${BASE_API_URL}/location/form-data`,
    POST_FACILITY_ARCHIVE: `${BASE_API_URL}/location/archive`,
    POST_FACILITY_STORE: `${BASE_API_URL}/location/store`,
    POST_USER_LIST: `${BASE_API_URL}/user/index`,
    POST_USER_FORMDATA: `${BASE_API_URL}/user/form-data`,
    POST_USER_ARCHIVE: `${BASE_API_URL}/user/archive`,
    POST_USER_STORE: `${BASE_API_URL}/user/store`,
    POST_PURCHASER_TYPE_LIST: `${BASE_API_URL}/purchaser-type/index`,
    POST_PURCHASER_TYPE_FORMDATA: `${BASE_API_URL}/purchaser-type/form-data`,
    POST_PURCHASER_TYPE_ARCHIVE: `${BASE_API_URL}/purchaser-type/archive`,
    POST_PURCHASER_TYPE_STORE: `${BASE_API_URL}/purchaser-type/store`,
    POST_REFERENCE_LIST: `${BASE_API_URL}/reference/index`,
    POST_REFERENCE_FORMDATA: `${BASE_API_URL}/reference/form-data`,
    POST_REFERENCE_ARCHIVE: `${BASE_API_URL}/reference/archive`,
    POST_REFERENCE_STORE: `${BASE_API_URL}/reference/store`,
    POST_APPOINTMENT_SERVICE_LIST: `${BASE_API_URL}/appointment-type/index`,
    POST_APPOINTMENT_SERVICE_FORMDATA: `${BASE_API_URL}/appointment-type/form-data`,
    POST_APPOINTMENT_SERVICE_ARCHIVE: `${BASE_API_URL}/appointment-type/archive`,
    POST_APPOINTMENT_SERVICE_STORE: `${BASE_API_URL}/appointment-type/store`,
    POST_PURCHASER_LIST: `${BASE_API_URL}/purchaser/index`,
    POST_PURCHASER_FORMDATA: `${BASE_API_URL}/purchaser/form-data`,
    POST_PURCHASER_ARCHIVE: `${BASE_API_URL}/purchaser/archive`,
    POST_PURCHASER_STORE: `${BASE_API_URL}/purchaser/store`,
    POST_TEMPLATE_LIST: `${BASE_API_URL}/template/index`,
    POST_TEMPLATE_FORMDATA: `${BASE_API_URL}/template/form-data`,
    POST_TEMPLATE_ARCHIVE: `${BASE_API_URL}/template/archive`,
    POST_TEMPLATE_STORE: `${BASE_API_URL}/template/store`,
    POST_CONSULTANT_HOURS_LIST: `${BASE_API_URL}/consultant-work-hour/index`,
    POST_CONSULTANT_HOURS_FORMDATA: `${BASE_API_URL}/consultant-work-hour/form-data`,
    POST_CONSULTANT_HOURS_ARCHIVE: `${BASE_API_URL}/consultant-work-hour/archive`,
    POST_CONSULTANT_HOURS_STORE: `${BASE_API_URL}/consultant-work-hour/store`,
    POST_CATEGORY_LIST: `${BASE_API_URL}/category/index`,
    POST_CATEGORY_FORMDATA: `${BASE_API_URL}/category/form-data`,
    POST_CATEGORY_ARCHIVE: `${BASE_API_URL}/category/archive`,
    POST_CATEGORY_STORE: `${BASE_API_URL}/category/store`,
    POST_CATEGORY_DEFAULT: `${BASE_API_URL}/category/default`,
    POST_TAX_LIST: `${BASE_API_URL}/tax/index`,
    POST_TAX_FORMDATA: `${BASE_API_URL}/tax/form-data`,
    POST_TAX_ARCHIVE: `${BASE_API_URL}/tax/archive`,
    POST_TAX_STORE: `${BASE_API_URL}/tax/store`,
    POST_TAX_DEFAULT: `${BASE_API_URL}/tax/default`,
    POST_RULE_LIST: `${BASE_API_URL}/rule/index`,
    POST_RULE_FORMDATA: `${BASE_API_URL}/rule/form-data`,
    POST_RULE_DELETE: `${BASE_API_URL}/rule/delete`,
    POST_RULE_STORE: `${BASE_API_URL}/rule/store`,
    POST_RULE_GET_RULES: `${BASE_API_URL}/rule/get-rule-details`,
    POST_DRUG_PATHWAY_LIST: `${BASE_API_URL}/drug-pathway/index`,
    POST_DRUG_PATHWAY_FORMDATA: `${BASE_API_URL}/drug-pathway/form-data`,
    POST_DRUG_PATHWAY_ARCHIVE: `${BASE_API_URL}/drug-pathway/archive`,
    POST_DRUG_PATHWAY_STORE: `${BASE_API_URL}/drug-pathway/store`,
    POST_DRUG_PATHWAY_DEFAULT: `${BASE_API_URL}/drug-pathway/default`,
    POST_DRUG_LIST: `${BASE_API_URL}/drug/index`,
    POST_DRUG_FORMDATA: `${BASE_API_URL}/drug/form-data`,
    POST_DRUG_DELETE: `${BASE_API_URL}/drug/delete`,
    POST_DRUG_STORE: `${BASE_API_URL}/drug/store`,


    POST_PATIENT_LIST: `${BASE_API_URL}/patient/index`,
    POST_PATIENT_FORMDATA: `${BASE_API_URL}/patient/form-data`,
    POST_PATIENT_ARCHIVE: `${BASE_API_URL}/patient/archive`,
    POST_PATIENT_STORE: `${BASE_API_URL}/patient/store`,
    POST_PATIENT_GETLIST: `${BASE_API_URL}/patient/get-list`,
    POST_ENCOUNTER_LIST: `${BASE_API_URL}/encounter/index`,
    POST_ENCOUNTER_FORMDATA: `${BASE_API_URL}/encounter/form-data`,
    POST_ENCOUNTER_STATUS: `${BASE_API_URL}/encounter/status`,
    POST_ENCOUNTER_STORE: `${BASE_API_URL}/encounter/store`,
    POST_ENCOUNTER_GETLIST: `${BASE_API_URL}/encounter/get-list`,
    POST_LETTER_LIST: `${BASE_API_URL}/letter/index`,
    POST_LETTER_FORMDATA: `${BASE_API_URL}/letter/form-data`,
    POST_LETTER_STATUS: `${BASE_API_URL}/letter/status`,
    POST_LETTER_STORE: `${BASE_API_URL}/letter/store`,
    POST_LETTER_GETLIST: `${BASE_API_URL}/letter/get-list`,
    POST_LETTER_GETCONTENT: `${BASE_API_URL}/letter/get-content`,
    POST_SCAN_LIST: `${BASE_API_URL}/scan/index`,
    POST_SCAN_FORMDATA: `${BASE_API_URL}/scan/form-data`,
    POST_SCAN_STATUS: `${BASE_API_URL}/scan/status`,
    POST_SCAN_STORE: `${BASE_API_URL}/scan/store`,
    POST_NOTE_LIST: `${BASE_API_URL}/patient-note/index`,
    POST_NOTE_FORMDATA: `${BASE_API_URL}/patient-note/form-data`,
    POST_NOTE_DELETE: `${BASE_API_URL}/patient-note/delete`,
    POST_NOTE_STORE: `${BASE_API_URL}/patient-note/store`,
    POST_SOAP_NOTE_LIST: `${BASE_API_URL}/soap-note/index`,
    POST_SOAP_NOTE_FORMDATA: `${BASE_API_URL}/soap-note/form-data`,
    POST_SOAP_NOTE_DELETE: `${BASE_API_URL}/soap-note/delete`,
    POST_SOAP_NOTE_STORE: `${BASE_API_URL}/soap-note/store`,

    
    POST_APPOINTMENT_LIST: `${BASE_API_URL}/appointment/index`,
    POST_APPOINTMENT_FORMDATA: `${BASE_API_URL}/appointment/form-data`,
    POST_APPOINTMENT_ARCHIVE: `${BASE_API_URL}/appointment/archive`,
    POST_APPOINTMENT_STORE: `${BASE_API_URL}/appointment/store`,
    POST_AVAILABLE_SLOTS: `${BASE_API_URL}/consultant-work-hour/available-slots`,
    POST_DAY_SLOTS: `${BASE_API_URL}/consultant-work-hour/day-slots`,
    POST_WEEK_SLOTS: `${BASE_API_URL}/consultant-work-hour/week-slots`,
    POST_MONTH_SLOTS: `${BASE_API_URL}/appointment/month`, 

    POST_SURGERY_LIST: `${BASE_API_URL}/surgery/index`,
    POST_SURGERY_FORMDATA: `${BASE_API_URL}/surgery/form-data`,
    POST_SURGERY_ARCHIVE: `${BASE_API_URL}/surgery/archive`,
    POST_SURGERY_STORE: `${BASE_API_URL}/surgery/store`,

    POST_INVOICE_LIST: `${BASE_API_URL}/invoice/index`,
    POST_INVOICE_GETLIST: `${BASE_API_URL}/invoice/get-list`,
    POST_INVOICE_FORMDATA: `${BASE_API_URL}/invoice/form-data`,
    POST_INVOICE_ARCHIVE: `${BASE_API_URL}/invoice/archive`,
    POST_INVOICE_STORE: `${BASE_API_URL}/invoice/store`,
    POST_RECEIPT_LIST: `${BASE_API_URL}/receipt/index`,
    POST_RECEIPT_FORMDATA: `${BASE_API_URL}/receipt/form-data`,
    POST_RECEIPT_ARCHIVE: `${BASE_API_URL}/receipt/archive`,
    POST_RECEIPT_STORE: `${BASE_API_URL}/receipt/store`,

    
    // PATCH METHODS
    PATCH_PATIENT: `${BASE_API_URL}/updatePatient`,

    // DELETE METHODS
    DELETE_PATIENT: `${BASE_API_URL}/deletePatient`,
};
export default ENDPOINTS;