export interface DrugModel {
    id?: number | null;
    category_id: number | null;
    code: string;
    bar_code: string;
    gms_number: string;
    trade_name: string;
    pack_size : string;
    pack_size_number: string;
    pack_size_units : string;
    manufacturer: string;
    agent: string;
    ingredient_cost : string;
    retail_price: string;
    vat: string;
    vat_change: string;
    coschange : string;
    poison_classification: string;
    product_authorisation: string;
    EHBLTINO: string;
    generic_name: string;
    drug_date : string;
    warning_code: string;
    ingred1: string;
    ingred2: string;
    ATC1 : string;
    ATC2 : string;
    dentist: string;
    counsel_code: string;
    strength: string;
    drug_from : string;
    ingredient1: string;
    ingredient2: string;
    ingredient3: string;
    ingredient4: string;
    ingredient5: string;
    ingredient6: string;
    ingredient7: string;
    ingredient8: string;
    ingredient9: string;
    ingredient10: string;
    IATC1: string;
    IATC2: string;
    IATC3: string;
    IATC4: string;
    IATC5: string;
    IATC6: string;
    IATC7: string;
    IATC8: string;
    IATC9: string;
    IATC10: string;
}